[package]
name = "sms-bridge-receiver"
version = "2.0.0"
edition = "2021"

[lib]
name = "sms_bridge_receiver_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
axum = "0.8.9"
hostname = "0.4.2"
local-ip-address = "0.6.13"
log = "0.4.33"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-autostart = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-log = "2"
tauri-plugin-notification = "2"
tauri-plugin-single-instance = "2"
tokio = { version = "1.53.1", features = ["net", "sync", "time"] }
tower-http = { version = "0.7.0", features = ["cors"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
